---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: simple-webapp
  labels:
    # apps.tanzu.vmware.com/is-dev: "true"
    # apps.tanzu.vmware.com/is-custom: "true"
    apps.tanzu.vmware.com/workload-type: web
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: simple-webapp
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  source:
    git:
      ref:
        branch: main
      url: https://github.com/jricho/simple-webapp.git
    # subPath: complete
  env:
    - name: GREETING_TEXT
      value: welcome from tanzu factory
  params:
#   - name: testing_pipeline_matching_labels # multi-pipeline functionality
#     value: {"apps.tanzu.vmware.com/pipeline":"test", "apps.tanzu.vmware.com/language":"java"} # multi-pipeline functionality
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: test-java    
    - name: api_descriptor
      value:
        type: openapi
        location: 
          path: "/v3/api-docs"
        owner: default-team
        system: demo
        description: "Demo Api Auto Rego"
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
