version: "3"

services:
  
  simplewebapp:
    container_name: simple-webapp
    build:
      context: .
      dockerfile: ./Dockerfile.devcontainer
    volumes:
      - ../:/workspace:cached
    environment:
      GREETING_TEXT: Hello from anahid !!
      # spring_profiles_active: pgsqllocal
    command: sleep infinity
    networks: 
      simplewebapp:
        ipv4_address: 172.28.0.5
    ports:
      - 8080:8080
    restart: unless-stopped
    stdin_open: true
    extra_hosts:
      - "kubernetes:127.0.0.1"

networks:
  simplewebapp:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
        